-- MySQL Version of Oracle PYS Database Tables
-- Converted from Oracle SQL to MySQL

-- Database creation
CREATE DATABASE IF NOT EXISTS pys;
USE pys;

-- Table 1: PYS_DEG_SEVIYE_AGIRLIK_TBL
CREATE TABLE PYS_DEG_SEVIYE_AGIRLIK_TBL (
    DEG_SEVIYE_NO INT NOT NULL AUTO_INCREMENT,
    SEVIYE_ID INT,
    DEGERLENDIRICI_SEVIYE_ID INT,
    AGIRLIK_AMIR DECIMAL(5,2),
    AGIRLIK_AMIR_DEGIL DECIMAL(5,2),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (DEG_SEVIYE_NO),
    INDEX FK_DEG_SEV_AG1 (SEVIYE_ID),
    INDEX FK_DEG_SEV_AG2 (DEGERLENDIRICI_SEVIYE_ID)
) ENGINE=InnoDB COMMENT='Değerlendirme seviye ağırlık tablosu';

-- Table 2: PYS_DEGERLENDIRME_TBL
CREATE TABLE PYS_DEGERLENDIRME_TBL (
    DEG_NO INT NOT NULL AUTO_INCREMENT,
    DEG_ALAN_PERS_DONEM_ID INT,
    DEG_VEREN_PERS_DONEM_ID INT,
    SORU_ID INT,
    SKALA_NO INT,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (DEG_NO),
    UNIQUE KEY UQ_PYS_DEG_TBL (DEG_ALAN_PERS_DONEM_ID, SORU_ID, DEG_VEREN_PERS_DONEM_ID),
    INDEX FK1_PYS_DEG_TBL (DEG_ALAN_PERS_DONEM_ID),
    INDEX FK2_PYS_DEG_TBL (DEG_VEREN_PERS_DONEM_ID),
    INDEX FK3_PYS_DEG_TBL (SORU_ID),
    INDEX FK4_PYS_DEG_TBL (SKALA_NO)
) ENGINE=InnoDB COMMENT='Değerlendirme tablosu';

-- Table 3: PYS_DO_LOG_TBL
CREATE TABLE PYS_DO_LOG_TBL (
    LOG_NO INT NOT NULL AUTO_INCREMENT,
    LOG_DONEM INT,
    LOG_YER VARCHAR(50),
    LOG_MESAJ VARCHAR(2000),
    LOG_TARIH DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LOG_NO)
) ENGINE=InnoDB COMMENT='Dönem log tablosu';

-- Table 4: PYS_DONEM_TBL
CREATE TABLE PYS_DONEM_TBL (
    DONEM_NO INT NOT NULL AUTO_INCREMENT,
    TESIS DECIMAL(4,0),
    DONEM_ADI VARCHAR(20),
    CAL_TIP VARCHAR(1),
    DONEM_BASLAMA DATE,
    DONEM_BITIS DATE,
    SAP_TRANSFER_TARIHI DATE,
    SKALA_TANIM_NO INT,
    HARF_SKALA_TANIM_NO INT,
    MIN_CAL_SURE INT,
    MAX_PUAN_FARKI INT,
    DONEM_DURUM TINYINT DEFAULT 1,
    TOPLAM_PUAN INT,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    SAP_TRANS_GER_TARIHI DATE,
    BEKLEME_ONC_DURUM TINYINT,
    PRIMARY KEY (DONEM_NO),
    UNIQUE KEY UQ_PYS_DONEM (TESIS, DONEM_ADI, CAL_TIP),
    INDEX FK_PYS_DONEM (SKALA_TANIM_NO),
    INDEX FK2_PYS_DONEM (HARF_SKALA_TANIM_NO)
) ENGINE=InnoDB COMMENT='Dönem tablosu';

-- Table 5: PYS_GB_ONAY_DURUMU_TBL
CREATE TABLE PYS_GB_ONAY_DURUMU_TBL (
    KAYIT_ID INT NOT NULL AUTO_INCREMENT,
    PERS_DONEM_ID INT,
    GB_ALMA_DURUMU INT DEFAULT 0,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (KAYIT_ID),
    INDEX FK_PYS_GB_ONAY_DURUMU (PERS_DONEM_ID)
) ENGINE=InnoDB COMMENT='Geri bildirim onay durumu tablosu';

-- Table 6: PYS_GERI_BILDIRIM_TBL
CREATE TABLE PYS_GERI_BILDIRIM_TBL (
    GB_ID INT NOT NULL AUTO_INCREMENT,
    GB_ALAN_PERS_DONEM_ID INT,
    GB_VEREN_PERS_DONEM_ID INT,
    GB_TARIHI DATE,
    GB_YER VARCHAR(100),
    GB_ACIKLAMA VARCHAR(600),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    GB_ALAN_ACIKLAMA VARCHAR(600),
    GB_DURUM TINYINT DEFAULT 0,
    GB_GUNCELLEME_DURUM VARCHAR(5),
    GB_SMS_GONDERIM_TARIHI DATE,
    GB_GUNCEL_ACIKLAMA_DURUM TINYINT DEFAULT 0,
    PRIMARY KEY (GB_ID),
    INDEX FK1_PYS_GERI_BILDIRIM (GB_ALAN_PERS_DONEM_ID),
    INDEX FK2_PYS_GERI_BILDIRIM (GB_VEREN_PERS_DONEM_ID)
) ENGINE=InnoDB COMMENT='Geri bildirim tablosu';

-- Table 7: PYS_HARF_SKALA_TANIM_TBL
CREATE TABLE PYS_HARF_SKALA_TANIM_TBL (
    HARF_SKALA_TANIM_NO INT NOT NULL AUTO_INCREMENT,
    TESIS DECIMAL(4,0),
    HARF_SKALA_ADI VARCHAR(50),
    SKALA_DURUM TINYINT,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (HARF_SKALA_TANIM_NO),
    UNIQUE KEY UQ_PYS_HARF_SKALA (TESIS, HARF_SKALA_ADI)
) ENGINE=InnoDB COMMENT='Harf skala tanım tablosu';

-- Table 8: PYS_HARF_SKALA_TBL
CREATE TABLE PYS_HARF_SKALA_TBL (
    HARF_SKALA_NO INT NOT NULL AUTO_INCREMENT,
    HARF_SKALA_TANIM_NO INT,
    HARF_SKALA_SIRA_NO INT,
    HARF_SKALA VARCHAR(1),
    DEGER1 DECIMAL(4,0),
    KRITER1 VARCHAR(2),
    DEGER2 DECIMAL(4,0),
    KRITER2 VARCHAR(2),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    ACIKLAMA VARCHAR(50),
    PRIMARY KEY (HARF_SKALA_NO),
    UNIQUE KEY UQ1_PYS_HARF_SKALA_DETAY (HARF_SKALA_TANIM_NO, HARF_SKALA_SIRA_NO),
    INDEX FK1_PYS_HARF_SKALA_DETAY (HARF_SKALA_TANIM_NO)
) ENGINE=InnoDB COMMENT='Harf skala tablosu';

-- Table 9: PYS_KADRO_TBL
CREATE TABLE PYS_KADRO_TBL (
    KADRO_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    POZ_KOD VARCHAR(9),
    POZ_AD VARCHAR(100),
    ORG_KOD VARCHAR(8),
    UNITE_KOD VARCHAR(8),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (KADRO_ID),
    UNIQUE KEY UQ_KADRO (DONEM_NO, POZ_KOD),
    INDEX FK_KADRO (DONEM_NO)
) ENGINE=InnoDB COMMENT='Kadro tablosu';

-- Table 10: PYS_ORG_SEVIYE_TANIM_TBL
CREATE TABLE PYS_ORG_SEVIYE_TANIM_TBL (
    SEVIYE_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    SEVIYE_KOD VARCHAR(4),
    SEVIYE_ADI VARCHAR(100),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (SEVIYE_ID),
    UNIQUE KEY UQ_PYS_ORG_SEVIYE (DONEM_NO, SEVIYE_KOD),
    INDEX FK_PYS_ORG_SEVIYE (DONEM_NO)
) ENGINE=InnoDB COMMENT='Organizasyon seviye tanım tablosu';

-- Table 11: PYS_ORG_TBL
CREATE TABLE PYS_ORG_TBL (
    ORG_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    ORG_KOD VARCHAR(8),
    ORG_AD VARCHAR(100),
    SEVIYE_KOD VARCHAR(4),
    UST_ORG_KOD VARCHAR(8),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (ORG_ID),
    INDEX FK_PYS_ORG (DONEM_NO),
    INDEX INDEX_ORG_KOD (ORG_KOD, UST_ORG_KOD)
) ENGINE=InnoDB COMMENT='Organizasyon tablosu';

-- Table 12: PYS_PERSONEL_DONEM_SONUC_TBL
CREATE TABLE PYS_PERSONEL_DONEM_SONUC_TBL (
    SONUC_ID INT NOT NULL AUTO_INCREMENT,
    PERS_DONEM_ID INT,
    SONUC_ONAY_ID INT,
    NIHAI_PUAN DECIMAL(3,0),
    ORG_ORT_PUAN DECIMAL(5,2),
    ORG_SIRASI INT,
    ORG_PERS_SAYISI INT,
    HARF_SKALASI VARCHAR(1),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    HARFGUNCELLEME TINYINT DEFAULT 0,
    PRIMARY KEY (SONUC_ID),
    INDEX FK1_PYS_SONUC (PERS_DONEM_ID),
    INDEX FK2_PYS_SONUC (SONUC_ONAY_ID)
) ENGINE=InnoDB COMMENT='Personel dönem sonuç tablosu';

-- Table 13: PYS_PERSONEL_TBL
CREATE TABLE PYS_PERSONEL_TBL (
    PERS_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    PER_NO VARCHAR(6),
    AD VARCHAR(40),
    SOYAD VARCHAR(40),
    KIMLIK_NO VARCHAR(12),
    EMAIL VARCHAR(100),
    TEL_IS VARCHAR(30),
    CAL_TIP VARCHAR(1),
    IS_GIR_TARIH DATE,
    AMIR_EH TINYINT,
    IS_KOD VARCHAR(8),
    IS_AD VARCHAR(100),
    POZISYON_KOD VARCHAR(8),
    POZISYON_AD VARCHAR(100),
    PER_ORG_KOD VARCHAR(8),
    PER_ORG_AD VARCHAR(100),
    UNITE_ORG_KOD VARCHAR(8),
    UNITE_ORG_AD VARCHAR(100),
    SEVIYE_KOD VARCHAR(4),
    GM_KOD VARCHAR(8),
    GM_AD VARCHAR(100),
    GMY_KOD VARCHAR(8),
    GMY_AD VARCHAR(100),
    GRPBAS_KOD VARCHAR(8),
    GRPBAS_AD VARCHAR(100),
    DIR_KOD VARCHAR(8),
    DIR_AD VARCHAR(100),
    MDR_KOD VARCHAR(8),
    MDR_AD VARCHAR(100),
    MDRYRD_KOD VARCHAR(8),
    MDRYRD_AD VARCHAR(100),
    BASSEF_KOD VARCHAR(8),
    BASSEF_AD VARCHAR(100),
    AMIRLIK_KOD VARCHAR(8),
    AMIRLIK_AD VARCHAR(100),
    PBFOR_KOD VARCHAR(8),
    PBFOR_AD VARCHAR(100),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    CALGRUP_KOD VARCHAR(2),
    CALGRUP_AD VARCHAR(50),
    PRIMARY KEY (PERS_ID),
    INDEX FK_PYS_PERSONEL (DONEM_NO)
) ENGINE=InnoDB COMMENT='Personel tablosu';

-- Table 14: PYS_SKALA_TANIM_TBL
CREATE TABLE PYS_SKALA_TANIM_TBL (
    SKALA_TANIM_NO INT NOT NULL AUTO_INCREMENT,
    TESIS DECIMAL(4,0),
    SKALA_ADI VARCHAR(50),
    SKALA_DURUM TINYINT DEFAULT 0,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (SKALA_TANIM_NO),
    UNIQUE KEY UQ_SKALA_TANIM (TESIS, SKALA_ADI)
) ENGINE=InnoDB COMMENT='Skala tanım tablosu';

-- Table 15: PYS_SKALA_TBL
CREATE TABLE PYS_SKALA_TBL (
    SKALA_NO INT NOT NULL AUTO_INCREMENT,
    SKALA_TANIM_NO INT,
    SKALA_SIRA_NO INT,
    SKALA_ACIKLAMA VARCHAR(20),
    SKALA_AGIRLIK DECIMAL(3,0),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (SKALA_NO),
    UNIQUE KEY UQ_PYS_SKALA (SKALA_TANIM_NO, SKALA_SIRA_NO),
    INDEX FK_PYS_SKALA (SKALA_TANIM_NO)
) ENGINE=InnoDB COMMENT='Skala tablosu';

-- Table 16: PYS_SORULAR_AKTARIM_TBL
CREATE TABLE PYS_SORULAR_AKTARIM_TBL (
    SIRA_NO INT,
    POZISYON_KOD VARCHAR(9),
    SORU_NO INT,
    SORU VARCHAR(500),
    SORU_ACIKLAMA VARCHAR(700),
    SORU_PUAN DECIMAL(5,2)
) ENGINE=InnoDB COMMENT='Sorular aktarım tablosu';

-- Table 17: PYS_SORULAR_TBL
CREATE TABLE PYS_SORULAR_TBL (
    SORU_ID INT NOT NULL AUTO_INCREMENT,
    KADRO_ID INT,
    SORU_NO INT NOT NULL,
    SORU VARCHAR(500) NOT NULL,
    SORU_ACIKLAMA VARCHAR(700),
    SORU_PUAN DECIMAL(5,2) NOT NULL,
    TIP TINYINT DEFAULT 0,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SORU_ID),
    INDEX FK_PYS_SORU (KADRO_ID)
) ENGINE=InnoDB COMMENT='Sorular tablosu';

-- Table 18: PYS_TRANSFER_TBL
CREATE TABLE PYS_TRANSFER_TBL (
    TRANSFER_ID INT NOT NULL AUTO_INCREMENT,
    PERS_DONEM_ID INT,
    YENI_IS_KOD VARCHAR(8),
    YENI_IS_AD VARCHAR(100),
    YENI_POZISYON_KOD VARCHAR(9),
    YENI_POZISYON_AD VARCHAR(100),
    YENI_PER_ORG_KOD VARCHAR(8),
    YENI_PER_ORG_AD VARCHAR(100),
    YENI_UNITE_ORG_KOD VARCHAR(8),
    YENI_UNITE_ORG_AD VARCHAR(100),
    TRANSFER_DURUM TINYINT,
    TRANSFER_TALEP_EDEN_PER_NO VARCHAR(6),
    TRANSFER_TALEP_SAAT DATETIME,
    TRANSFER_ONAY_PER VARCHAR(6),
    TRANSFER_ONAY_SAAT DATETIME,
    TRANSFER_ONAY_IPTAL_PER VARCHAR(6),
    TRANSFER_ONAY_IPTAL_SAAT DATETIME,
    TRANSFER_ACIKLAMA VARCHAR(500),
    PRIMARY KEY (TRANSFER_ID),
    INDEX FK1_TRANSFER_TBL (PERS_DONEM_ID)
) ENGINE=InnoDB COMMENT='Transfer tablosu';

-- Table 19: PYS_UNITE_SONUC_ONAY_TBL
CREATE TABLE PYS_UNITE_SONUC_ONAY_TBL (
    SONUC_ONAY_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    PERS_DONEM_ID INT,
    UNITE_KOD VARCHAR(8),
    DURUM TINYINT,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (SONUC_ONAY_ID),
    UNIQUE KEY PYS_UNITE_SONUC_ONAY_TBL_UK1 (DONEM_NO, PERS_DONEM_ID, UNITE_KOD, DURUM),
    INDEX FK1_PYS_SONUC_ONAY (DONEM_NO),
    INDEX FK2_PYS_SONUC_ONAY (PERS_DONEM_ID)
) ENGINE=InnoDB COMMENT='Ünite sonuç onay tablosu';

-- Table 20: PYS_UNVAN_TBL
CREATE TABLE PYS_UNVAN_TBL (
    UNVAN_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT,
    IS_KOD VARCHAR(8),
    IS_AD VARCHAR(100),
    CAL_TIP VARCHAR(1),
    AMIR_EH TINYINT,
    OPER VARCHAR(6),
    OPER_SAAT DATETIME,
    PRIMARY KEY (UNVAN_ID),
    UNIQUE KEY UQ_PYS_UNVAN (DONEM_NO, IS_KOD, CAL_TIP, AMIR_EH),
    INDEX FK_PYS_UNVAN (DONEM_NO)
) ENGINE=InnoDB COMMENT='Ünvan tablosu';

-- Table 21: PYS_VA_ATAMA_TBL
CREATE TABLE PYS_VA_ATAMA_TBL (
    VA_ATAMA_ID INT NOT NULL AUTO_INCREMENT,
    DONEM_NO INT NOT NULL,
    CALISAN_PER_NO VARCHAR(6) NOT NULL,
    VA_PER_NO VARCHAR(6) NOT NULL,
    DURUM TINYINT DEFAULT 0 NOT NULL,
    OPER VARCHAR(6) NOT NULL,
    OPER_SAAT DATETIME NOT NULL,
    PRIMARY KEY (VA_ATAMA_ID),
    UNIQUE KEY UQ_VA_ATAMA (DONEM_NO, CALISAN_PER_NO, VA_PER_NO),
    INDEX FK1_VA_ATAMA (DONEM_NO)
) ENGINE=InnoDB COMMENT='Vekil atama tablosu';

-- Table 22: PYSPARAMETRELER
CREATE TABLE PYSPARAMETRELER (
    ID INT NOT NULL AUTO_INCREMENT,
    PARAMETREADI VARCHAR(50),
    PARAMETREDEGERI VARCHAR(100),
    PARAMETRETIPI VARCHAR(10),
    DURUM TINYINT DEFAULT 1 NOT NULL,
    PARAMETREDEGERI4000 TEXT,
    PRIMARY KEY (ID)
) ENGINE=InnoDB COMMENT='PYS parametreler tablosu';

-- Table 23: PYS_PERSONEL_DONEM_TBL (Oracle sql23.sql'den dönüştürülmüş tam versiyon)
CREATE TABLE PYS_PERSONEL_DONEM_TBL (
    PERS_DONEM_ID INT NOT NULL AUTO_INCREMENT,
    PERS_ID INT,
    DONEM_NO INT,
    PER_NO VARCHAR(6),
    AD VARCHAR(40),
    SOYAD VARCHAR(40),
    KIMLIK_NO VARCHAR(12),
    EMAIL VARCHAR(100),
    TEL_IS VARCHAR(30),
    CAL_TIP VARCHAR(1),
    IS_GIR_TARIH DATE,
    AMIR_EH TINYINT,
    IS_KOD VARCHAR(8),
    IS_AD VARCHAR(100),
    POZISYON_KOD VARCHAR(9),
    POZISYON_AD VARCHAR(100),
    PER_ORG_KOD VARCHAR(8),
    PER_ORG_AD VARCHAR(100),
    UNITE_ORG_KOD VARCHAR(8),
    UNITE_ORG_AD VARCHAR(100),
    SEVIYE_KOD VARCHAR(4),
    DEG_DURUMU TINYINT DEFAULT 0 COMMENT '0:Değerlendirme yapılacak 1:Değerlendirme yapılmayacak 2:Eksik çalışmadan dolayı değerlendirme yapılmayacak 3:Geri Bildirim verilmeyecek.',
    KAYIT_TIPI TINYINT DEFAULT 0 COMMENT '0:Asil(Default) 1:Vekaleten 2:Transfer',
    GM_KOD VARCHAR(8),
    GM_AD VARCHAR(100),
    GMY_KOD VARCHAR(8),
    GMY_AD VARCHAR(100),
    GRPBAS_KOD VARCHAR(8),
    GRPBAS_AD VARCHAR(100),
    DIR_KOD VARCHAR(8),
    DIR_AD VARCHAR(100),
    MDR_KOD VARCHAR(8),
    MDR_AD VARCHAR(100),
    MDRYRD_KOD VARCHAR(8),
    MDRYRD_AD VARCHAR(100),
    BASSEF_KOD VARCHAR(8),
    BASSEF_AD VARCHAR(100),
    AMIRLIK_KOD VARCHAR(8),
    AMIRLIK_AD VARCHAR(100),
    PBFOR_KOD VARCHAR(8),
    PBFOR_AD VARCHAR(100),
    OPER VARCHAR(6),
    OPER_SAAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CALGRUP_KOD VARCHAR(2),
    CALGRUP_AD VARCHAR(50),
    TEL_CEP VARCHAR(30),
    PRIMARY KEY (PERS_DONEM_ID),
    INDEX IND_PER_ORG_KOD (PER_ORG_KOD),
    INDEX PYS_PERSONEL_DONEM_TBL_INDEX1 (DONEM_NO)
) ENGINE=InnoDB COMMENT='Personel dönem ilişki tablosu - Personellerin dönemsel durumlarını ve detay bilgilerini tutar';

-- Foreign Key Constraints
ALTER TABLE PYS_DEG_SEVIYE_AGIRLIK_TBL 
ADD CONSTRAINT FK_DEG_SEV_AG1 FOREIGN KEY (SEVIYE_ID) REFERENCES PYS_ORG_SEVIYE_TANIM_TBL(SEVIYE_ID),
ADD CONSTRAINT FK_DEG_SEV_AG2 FOREIGN KEY (DEGERLENDIRICI_SEVIYE_ID) REFERENCES PYS_ORG_SEVIYE_TANIM_TBL(SEVIYE_ID);

ALTER TABLE PYS_DEGERLENDIRME_TBL 
ADD CONSTRAINT FK1_PYS_DEG_TBL FOREIGN KEY (DEG_ALAN_PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID),
ADD CONSTRAINT FK2_PYS_DEG_TBL FOREIGN KEY (DEG_VEREN_PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID),
ADD CONSTRAINT FK3_PYS_DEG_TBL FOREIGN KEY (SORU_ID) REFERENCES PYS_SORULAR_TBL(SORU_ID),
ADD CONSTRAINT FK4_PYS_DEG_TBL FOREIGN KEY (SKALA_NO) REFERENCES PYS_SKALA_TBL(SKALA_NO);

ALTER TABLE PYS_DONEM_TBL 
ADD CONSTRAINT FK_PYS_DONEM FOREIGN KEY (SKALA_TANIM_NO) REFERENCES PYS_SKALA_TANIM_TBL(SKALA_TANIM_NO),
ADD CONSTRAINT FK2_PYS_DONEM FOREIGN KEY (HARF_SKALA_TANIM_NO) REFERENCES PYS_HARF_SKALA_TANIM_TBL(HARF_SKALA_TANIM_NO);

ALTER TABLE PYS_GB_ONAY_DURUMU_TBL 
ADD CONSTRAINT FK_PYS_GB_ONAY_DURUMU FOREIGN KEY (PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID);

ALTER TABLE PYS_GERI_BILDIRIM_TBL 
ADD CONSTRAINT FK1_PYS_GERI_BILDIRIM FOREIGN KEY (GB_ALAN_PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID),
ADD CONSTRAINT FK2_PYS_GERI_BILDIRIM FOREIGN KEY (GB_VEREN_PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID);

ALTER TABLE PYS_HARF_SKALA_TBL 
ADD CONSTRAINT FK1_PYS_HARF_SKALA_DETAY FOREIGN KEY (HARF_SKALA_TANIM_NO) REFERENCES PYS_HARF_SKALA_TANIM_TBL(HARF_SKALA_TANIM_NO);

ALTER TABLE PYS_KADRO_TBL 
ADD CONSTRAINT FK_KADRO FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_ORG_SEVIYE_TANIM_TBL 
ADD CONSTRAINT FK_PYS_ORG_SEVIYE FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_ORG_TBL 
ADD CONSTRAINT FK_PYS_ORG FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_PERSONEL_DONEM_SONUC_TBL 
ADD CONSTRAINT FK1_PYS_SONUC FOREIGN KEY (PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID),
ADD CONSTRAINT FK2_PYS_SONUC FOREIGN KEY (SONUC_ONAY_ID) REFERENCES PYS_UNITE_SONUC_ONAY_TBL(SONUC_ONAY_ID);

ALTER TABLE PYS_PERSONEL_TBL 
ADD CONSTRAINT FK_PYS_PERSONEL FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_PERSONEL_DONEM_TBL 
ADD CONSTRAINT FK_PYS_PERSDONEM FOREIGN KEY (PERS_ID) REFERENCES PYS_PERSONEL_TBL(PERS_ID),
ADD CONSTRAINT FK2_PYS_PERSDONEM FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_SKALA_TBL 
ADD CONSTRAINT FK_PYS_SKALA FOREIGN KEY (SKALA_TANIM_NO) REFERENCES PYS_SKALA_TANIM_TBL(SKALA_TANIM_NO);

ALTER TABLE PYS_SORULAR_TBL 
ADD CONSTRAINT FK_PYS_SORU FOREIGN KEY (KADRO_ID) REFERENCES PYS_KADRO_TBL(KADRO_ID);

ALTER TABLE PYS_TRANSFER_TBL 
ADD CONSTRAINT FK1_TRANSFER_TBL FOREIGN KEY (PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID);

ALTER TABLE PYS_UNITE_SONUC_ONAY_TBL 
ADD CONSTRAINT FK1_PYS_SONUC_ONAY FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO),
ADD CONSTRAINT FK2_PYS_SONUC_ONAY FOREIGN KEY (PERS_DONEM_ID) REFERENCES PYS_PERSONEL_DONEM_TBL(PERS_DONEM_ID);

ALTER TABLE PYS_UNVAN_TBL 
ADD CONSTRAINT FK_PYS_UNVAN FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

ALTER TABLE PYS_VA_ATAMA_TBL 
ADD CONSTRAINT FK1_VA_ATAMA FOREIGN KEY (DONEM_NO) REFERENCES PYS_DONEM_TBL(DONEM_NO);

-- Note: Oracle triggers converted to MySQL AUTO_INCREMENT
-- The original Oracle triggers for auto-incrementing IDs are replaced with AUTO_INCREMENT in MySQL
-- SYSDATE converted to CURRENT_TIMESTAMP
-- Oracle NUMBER data types converted to appropriate MySQL types (INT, DECIMAL, TINYINT)
-- Oracle VARCHAR2 converted to VARCHAR
-- Oracle storage and tablespace parameters removed (not applicable in MySQL)
-- Oracle schema quotes removed
